code --install-extension 13xforever.language-x86-64-assembly
code --install-extension aaron-bond.better-comments
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension blanu.vscode-styled-jsx
code --install-extension burkeholland.simple-react-snippets
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension fauna.faunadb
code --install-extension formulahendry.code-runner
code --install-extension golang.go
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension LeetCode.vscode-leetcode
code --install-extension maziac.asm-code-lens
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.LiveServer
code --install-extension skyran.js-jsx-snippets
code --install-extension toba.vsfire
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension yzhang.markdown-all-in-one
