code --install-extension 13xforever.language-x86-64-assembly
code --install-extension aaron-bond.better-comments
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension blanu.vscode-styled-jsx
code --install-extension burkeholland.simple-react-snippets
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension fauna.faunadb
code --install-extension formulahendry.code-runner
code --install-extension golang.go
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension LeetCode.vscode-leetcode
code --install-extension maziac.asm-code-lens
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.LiveServer
code --install-extension skyran.js-jsx-snippets
code --install-extension toba.vsfire
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension yzhang.markdown-all-in-one
code --install-extension 13xforever.language-x86-64-assembly
code --install-extension 42Crunch.vscode-openapi
code --install-extension aaron-bond.better-comments
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension BendixMa.dart-data-class-generator
code --install-extension blanu.vscode-styled-jsx
code --install-extension burkeholland.simple-react-snippets
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension EQuimper.react-native-react-redux
code --install-extension esbenp.prettier-vscode
code --install-extension fauna.faunadb
code --install-extension formulahendry.code-runner
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension icrawl.discord-vscode
code --install-extension jeroen-meijer.pubspec-assist
code --install-extension LeetCode.vscode-leetcode
code --install-extension maziac.asm-code-lens
code --install-extension michelemelluso.gitignore
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.vscode-react-native
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension skyran.js-jsx-snippets
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension toba.vsfire
code --install-extension Tyriar.lorem-ipsum
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension WakaTime.vscode-wakatime
code --install-extension yzhang.markdown-all-in-one
code --install-extension zoellner.openapi-preview
